// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListNodeDeploymentRequestsParams creates a new ListNodeDeploymentRequestsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListNodeDeploymentRequestsParams() *ListNodeDeploymentRequestsParams {
	return &ListNodeDeploymentRequestsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListNodeDeploymentRequestsParamsWithTimeout creates a new ListNodeDeploymentRequestsParams object
// with the ability to set a timeout on a request.
func NewListNodeDeploymentRequestsParamsWithTimeout(timeout time.Duration) *ListNodeDeploymentRequestsParams {
	return &ListNodeDeploymentRequestsParams{
		timeout: timeout,
	}
}

// NewListNodeDeploymentRequestsParamsWithContext creates a new ListNodeDeploymentRequestsParams object
// with the ability to set a context for a request.
func NewListNodeDeploymentRequestsParamsWithContext(ctx context.Context) *ListNodeDeploymentRequestsParams {
	return &ListNodeDeploymentRequestsParams{
		Context: ctx,
	}
}

// NewListNodeDeploymentRequestsParamsWithHTTPClient creates a new ListNodeDeploymentRequestsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListNodeDeploymentRequestsParamsWithHTTPClient(client *http.Client) *ListNodeDeploymentRequestsParams {
	return &ListNodeDeploymentRequestsParams{
		HTTPClient: client,
	}
}

/* ListNodeDeploymentRequestsParams contains all the parameters to send to the API endpoint
   for the list node deployment requests operation.

   Typically these are written to a http.Request.
*/
type ListNodeDeploymentRequestsParams struct {

	// ClusterID.
	ClusterID string

	// Dc.
	DC string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list node deployment requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNodeDeploymentRequestsParams) WithDefaults() *ListNodeDeploymentRequestsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list node deployment requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNodeDeploymentRequestsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) WithTimeout(timeout time.Duration) *ListNodeDeploymentRequestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) WithContext(ctx context.Context) *ListNodeDeploymentRequestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) WithHTTPClient(client *http.Client) *ListNodeDeploymentRequestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) WithClusterID(clusterID string) *ListNodeDeploymentRequestsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDC adds the dc to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) WithDC(dc string) *ListNodeDeploymentRequestsParams {
	o.SetDC(dc)
	return o
}

// SetDC adds the dc to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) SetDC(dc string) {
	o.DC = dc
}

// WithProjectID adds the projectID to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) WithProjectID(projectID string) *ListNodeDeploymentRequestsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list node deployment requests params
func (o *ListNodeDeploymentRequestsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListNodeDeploymentRequestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.DC); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
